name: topopt
channels:
  - conda-forge
  - defaults
dependencies:
  - alsa-lib=1.2.3=h516909a_0
  - ampl-mp=3.1.0=h2cc385e_1006
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - binutils_linux-64=2.36=hf3e587d_9
  - boost-cpp=1.74.0=h6cacc03_7
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py39hf3d152e_2
  - cmake=3.23.1=h5432695_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - ipopt=3.14.4
  - cyipopt=1.1.0
  - dbus=1.13.6=h5008d03_3
  - eigen=3.4.0=h4bd325d_0
  - expat=2.4.8=h27087fc_0
  - fenics=2019.1.0=py39hf3d152e_29
  - fenics-dijitso=2019.1.0=py39hf3d152e_29
  - fenics-dolfin=2019.1.0=py39h2b99043_29
  - fenics-ffc=2019.1.0=py39hf3d152e_29
  - fenics-fiat=2019.1.0=py39hf3d152e_29
  - fenics-libdolfin=2019.1.0=h5416c5e_29
  - fenics-ufl=2019.1.0=py39hf3d152e_29
  - fftw=3.3.10=mpi_mpich_h8b92f0a_2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h8e229c2_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.33.0=py39hb9d737c_0
  - freetype=2.10.4=h0708190_1
  - future=0.18.2=py39hf3d152e_5
  - gcc_impl_linux-64=10.3.0=hf2f2afa_15
  - gcc_linux-64=10.3.0=hc39de41_9
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h36c2ea0_2
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py39h78fa15d_0
  - gst-plugins-base=1.20.1=hcf0ee16_1
  - gstreamer=1.20.1=hd4edc92_1
  - gxx_impl_linux-64=10.3.0=hf2f2afa_15
  - gxx_linux-64=10.3.0=h2593f52_9
  - hdf5=1.12.1=mpi_mpich_h5d83325_4
  - hypre=2.24.0=mpi_mpich_h0faba72_0
  - icu=69.1=h9c3ff4c_0
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h166bdaf_1
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.2=py39hf939315_1
  - krb5=1.19.3=h08a2579_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=14_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=14_linux64_openblas
  - libclang=13.0.1=default_hc23dcda_0
  - libcurl=7.82.0=h2283fc2_0
  - libdeflate=1.10=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h28343ad_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-devel_linux-64=10.3.0=he6cfe16_15
  - libgcc-ng=11.2.0=h1d223b6_15
  - libgfortran-ng=11.2.0=h69a702a_15
  - libgfortran5=11.2.0=h5c6108e_15
  - libglib=2.70.2=h174f98d_4
  - libgomp=11.2.0=h1d223b6_15
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=14_linux64_openblas
  - libllvm13=13.0.1=hf817b99_2
  - libnghttp2=1.47.0=he49606f_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.20=pthreads_h78a6416_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=14.2=h676c864_0
  - libsanitizer=10.3.0=h26c7422_15
  - libssh2=1.10.0=ha35d2d1_2
  - libstdcxx-devel_linux-64=10.3.0=he6cfe16_15
  - libstdcxx-ng=11.2.0=he4da1e4_15
  - libtiff=4.3.0=h542a066_3
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.43.0=h7f98852_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h885dcf4_1
  - libzlib=1.2.11=h166bdaf_1014
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib=3.5.1=py39hf3d152e_0
  - matplotlib-base=3.5.1=py39h2fa2bec_0
  - metis=5.1.0=h58526e2_1006
  - mpc=1.2.1=h9f54685_0
  - mpfr=4.1.0=h9202a9a_1
  - mpi=1.0=mpich
  - mpi4py=3.1.3=py39h32b9844_1
  - mpich=4.0.2=h846660c_100
  - mpmath=1.2.1=pyhd8ed1ab_0
  - mumps-include=5.2.1=ha770c72_11
  - mumps-mpi=5.2.1=h7ee95aa_11
  - mumps-seq=5.2.1=h2104b81_11
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.28=h26416b9_4
  - mysql-libs=8.0.28=hbc51c84_4
  - ncurses=6.3=h27087fc_1
  - nspr=4.32=h9c3ff4c_1
  - nss=3.77=h2350873_0
  - numpy=1.22.0=py39h91f2184_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.0.2=h166bdaf_1
  - packaging=21.3=pyhd8ed1ab_0
  - parmetis=4.0.3=h2a9763c_1005
  - pcre=8.45=h9c3ff4c_0
  - petsc=3.16.6=real_h6e9d0b6_100
  - petsc4py=3.16.6=real_h016f20b_100
  - pillow=9.1.0=py39hae2aec6_2
  - pip=21.3.1=pyhd8ed1ab_0
  - pkg-config=0.29.2=h36c2ea0_1008
  - pkgconfig=1.5.5=py39hf3d152e_2
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptscotch=6.0.9=hb499603_2
  - pybind11=2.9.2=py39hf939315_1
  - pybind11-global=2.9.2=py39hf939315_1
  - pyparsing=3.0.8=pyhd8ed1ab_0
  - pyqt=5.12.3=py39hf3d152e_8
  - pyqt-impl=5.12.3=py39hde8b62d_8
  - pyqt5-sip=4.19.18=py39he80948d_8
  - pyqtchart=5.12=py39h0fcd23e_8
  - pyqtwebengine=5.12.1=py39h0fcd23e_8
  - python=3.9.12=h2660328_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - qt=5.12.9=h1304e3e_6
  - readline=8.1=h46c0cb4_0
  - rhash=1.4.1=h7f98852_0
  - scalapack=2.2.0=hd931219_1
  - scikit-umfpack=0.3.2=py39h5c8cd5b_1004
  - scipy=1.7.3=py39hee8e79c_0
  - scotch=6.0.9=hb2e6521_2
  - setuptools=62.1.0=py39hf3d152e_0
  - six=1.16.0=pyh6c4a22f_0
  - slepc=3.16.1=real_h7bbb3bb_101
  - slepc4py=3.16.1=real_hd623573_100
  - sqlite=3.38.2=h4ff8645_0
  - suitesparse=5.10.1=h9e50725_1
  - superlu=5.2.2=h16cfea0_0
  - superlu_dist=7.2.0=h25dcc4a_0
  - sympy=1.10.1=py39hf3d152e_0
  - sysroot_linux-64=2.12=he073ed8_15
  - tbb=2021.5.0=h924138e_1
  - tk=8.6.12=h27826a3_0
  - tornado=6.1=py39hb9d737c_3
  - tzdata=2022a=h191b570_0
  - unicodedata2=14.0.0=py39hb9d737c_1
  - unixodbc=2.3.9=hb166930_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.11=h166bdaf_1014
  - zstd=1.5.2=ha95c52a_0
  - pip:
      - git+https://github.com/dolfin-adjoint/pyadjoint.git@2019.1.2

